<?php

/*
  Plugin Name: Comunas de Chile para WooCommerce
  Plugin URI: http://www.sitiowebonline.cl
  Description: Este plugin activa las Comunas de Chile para WooCommerce.
  Version: 0.1
  Author: Anyda SRL <areyes@anyda.cl>
  Author URI: http://www.sitiowebonline.cl
  License: GPLv3
  Requires at least: 3.0 +
  Tested up to: 4.2
 */
/*
 *      Copyright 2015 Anyda SRL <areyes@anyda.cl>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 3 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

function comunas_de_chile($states) {
    $states['CL'] = array(
        '100' => 'Algarrobo',
        '101' => 'Alhué',
        '102' => 'Alto Biobío',
        '103' => 'Alto del Carmen',
        '104' => 'Alto Hospicio',
        '105' => 'Ancud',
        '106' => 'Andacollo',
        '107' => 'Angol',
        '108' => 'Antártica',
        '109' => 'Antofagasta',
        '110' => 'Antuco',
        '111' => 'Arauco',
        '112' => 'Arica',
        '113' => 'Aysén',
        '114' => 'Buin',
        '115' => 'Bulnes',
        '116' => 'Cabildo',
        '117' => 'Cabo de Hornos',
        '118' => 'Cabrero',
        '119' => 'Calama',
        '120' => 'Calbuco',
        '121' => 'Caldera',
        '122' => 'Calera de Tango',
        '123' => 'Calle Larga',
        '124' => 'Camarones',
        '125' => 'Camiña',
        '126' => 'Canela',
        '127' => 'Cañete',
        '128' => 'Carahue',
        '129' => 'Cartagena',
        '130' => 'Casablanca',
        '131' => 'Castro',
        '132' => 'Catemu',
        '133' => 'Cauquenes',
        '134' => 'Cerrillos',
        '135' => 'Cerro Navia',
        '136' => 'Chaitén',
        '137' => 'Chanco',
        '138' => 'Chañaral',
        '139' => 'Chépica',
        '140' => 'Chiguayante',
        '141' => 'Chile Chico',
        '142' => 'Chillán',
        '143' => 'Chillán Viejo',
        '144' => 'Chimbarongo',
        '145' => 'Cholchol',
        '146' => 'Chonchi',
        '147' => 'Cisnes',
        '148' => 'Cobquecura',
        '149' => 'Cochamó',
        '150' => 'Cochrane',
        '151' => 'Codegua',
        '152' => 'Coelemu',
        '153' => 'Coihueco',
        '154' => 'Coinco',
        '155' => 'Colbún',
        '156' => 'Colchane',
        '157' => 'Colina',
        '158' => 'Collipulli',
        '159' => 'Coltauco',
        '160' => 'Combarbalá',
        '161' => 'Concepción',
        '162' => 'Conchalí',
        '163' => 'Concón',
        '164' => 'Constitución',
        '165' => 'Contulmo',
        '166' => 'Copiapó',
        '167' => 'Coquimbo',
        '168' => 'Coronel',
        '169' => 'Corral',
        '170' => 'Coyhaique',
        '171' => 'Cunco',
        '172' => 'Curacautín',
        '173' => 'Curacaví',
        '174' => 'Curaco de Vélez',
        '175' => 'Curanilahue',
        '176' => 'Curarrehue',
        '177' => 'Curepto',
        '178' => 'Curicó',
        '179' => 'Dalcahue',
        '180' => 'Diego de Almagro',
        '181' => 'Doñihue',
        '182' => 'El Bosque',
        '183' => 'El Carmen',
        '184' => 'El Monte',
        '185' => 'El Quisco',
        '186' => 'El Tabo',
        '187' => 'Empedrado',
        '188' => 'Ercilla',
        '189' => 'Estación Central',
        '190' => 'Florida',
        '191' => 'Freire',
        '192' => 'Freirina',
        '193' => 'Fresia',
        '194' => 'Frutillar',
        '195' => 'Futaleufú',
        '196' => 'Futrono',
        '197' => 'Galvarino',
        '198' => 'General Lagos',
        '199' => 'Gorbea',
        '200' => 'Graneros',
        '201' => 'Guaitecas',
        '202' => 'Hijuelas',
        '203' => 'Hualaihué',
        '204' => 'Hualañé',
        '205' => 'Hualpén',
        '206' => 'Hualqui',
        '207' => 'Huara',
        '208' => 'Huasco',
        '209' => 'Huechuraba',
        '210' => 'Illapel',
        '211' => 'Independencia',
        '212' => 'Iquique',
        '213' => 'Isla de Maipo',
        '214' => 'Isla de Pascua',
        '215' => 'Juan Fernández',
        '216' => 'La Calera',
        '217' => 'La Cisterna',
        '218' => 'La Cruz',
        '219' => 'La Estrella',
        '220' => 'La Florida',
        '221' => 'La Granja',
        '222' => 'La Higuera',
        '223' => 'La Ligua',
        '224' => 'La Pintana',
        '225' => 'La Reina',
        '226' => 'La Serena',
        '227' => 'La Unión',
        '228' => 'Lago Ranco',
        '229' => 'Lago Verde',
        '230' => 'Laguna Blanca',
        '231' => 'Laja',
        '232' => 'Lampa',
        '233' => 'Lanco',
        '234' => 'Las Cabras',
        '235' => 'Las Condes',
        '236' => 'Lautaro',
        '237' => 'Lebu',
        '238' => 'Licantén',
        '239' => 'Limache',
        '240' => 'Linares',
        '241' => 'Litueche',
        '242' => 'Llanquihue',
        '243' => 'Llay Llay',
        '244' => 'Lo Barnechea',
        '245' => 'Lo Espejo',
        '246' => 'Lo Prado',
        '247' => 'Lolol',
        '248' => 'Loncoche',
        '249' => 'Longaví',
        '250' => 'Lonquimay',
        '251' => 'Los Álamos',
        '252' => 'Los Andes',
        '253' => 'Los Ángeles',
        '254' => 'Los Lagos',
        '255' => 'Los Muermos',
        '256' => 'Los Sauces',
        '257' => 'Los Vilos',
        '258' => 'Lota',
        '259' => 'Lumaco',
        '260' => 'Machalí',
        '261' => 'Macul',
        '262' => 'Máfil',
        '263' => 'Maipú',
        '264' => 'Malloa',
        '265' => 'Marchihue',
        '266' => 'María Elena',
        '267' => 'María Pinto',
        '268' => 'Mariquina',
        '269' => 'Maule',
        '270' => 'Maullín',
        '271' => 'Mejillones',
        '272' => 'Melipeuco',
        '273' => 'Melipilla',
        '274' => 'Molina',
        '275' => 'Monte Patria',
        '276' => 'Mostazal',
        '277' => 'Mulchén',
        '278' => 'Nacimiento',
        '279' => 'Nancagua',
        '280' => 'Natales',
        '281' => 'Navidad',
        '282' => 'Negrete',
        '283' => 'Ninhue',
        '284' => 'Nogales',
        '285' => 'Nueva Imperial',
        '286' => 'Ñiquén',
        '287' => 'Ñuñoa',
        '288' => 'O\'Higgins',
        '289' => 'Olivar',
        '290' => 'Ollagüe',
        '291' => 'Olmué',
        '292' => 'Osorno',
        '293' => 'Ovalle',
        '294' => 'Padre Hurtado',
        '295' => 'Padre las Casas',
        '296' => 'Paihuano',
        '297' => 'Paillaco',
        '298' => 'Paine',
        '299' => 'Palena',
        '300' => 'Palmilla',
        '301' => 'Panguipulli',
        '302' => 'Panquehue',
        '303' => 'Papudo',
        '304' => 'Paredones',
        '305' => 'Parral',
        '306' => 'Pedro Aguirre Cerda',
        '307' => 'Pelarco',
        '308' => 'Pelluhue',
        '309' => 'Pemuco',
        '310' => 'Pencahue',
        '311' => 'Penco',
        '312' => 'Peñaflor',
        '313' => 'Peñalolén',
        '314' => 'Peralillo',
        '315' => 'Perquenco',
        '316' => 'Petorca',
        '317' => 'Peumo',
        '318' => 'Pica',
        '319' => 'Pichidegua',
        '320' => 'Pichilemu',
        '321' => 'Pinto',
        '322' => 'Pirque',
        '323' => 'Pitrufquén',
        '324' => 'Placilla',
        '325' => 'Portezuelo',
        '326' => 'Porvenir',
        '327' => 'Pozo Almonte',
        '328' => 'Primavera',
        '329' => 'Providencia',
        '330' => 'Puchuncaví',
        '331' => 'Pucón',
        '332' => 'Pudahuel',
        '333' => 'Puente Alto',
        '334' => 'Puerto Montt',
        '335' => 'Puerto Octay',
        '336' => 'Puerto Varas',
        '337' => 'Pumanque',
        '338' => 'Punitaqui',
        '339' => 'Punta Arenas',
        '340' => 'Puqueldón',
        '341' => 'Purén',
        '342' => 'Purranque',
        '343' => 'Putaendo',
        '344' => 'Putre',
        '345' => 'Puyehue',
        '346' => 'Queilén',
        '347' => 'Quellón',
        '348' => 'Quemchi',
        '349' => 'Quilaco',
        '350' => 'Quilicura',
        '351' => 'Quilleco',
        '352' => 'Quillón',
        '353' => 'Quillota',
        '354' => 'Quilpué',
        '355' => 'Quinchao',
        '356' => 'Quinta de Tilcoco',
        '357' => 'Quinta Normal',
        '358' => 'Quintero',
        '359' => 'Quirihue',
        '360' => 'Rancagua',
        '361' => 'Ránquil',
        '362' => 'Rauco',
        '363' => 'Recoleta',
        '364' => 'Renaico',
        '365' => 'Renca',
        '366' => 'Rengo',
        '367' => 'Requínoa',
        '368' => 'Retiro',
        '369' => 'Rinconada',
        '370' => 'Río Bueno',
        '371' => 'Río Claro',
        '372' => 'Río Hurtado',
        '373' => 'Río Ibáñez',
        '374' => 'Río Negro',
        '375' => 'Río Verde',
        '376' => 'Romeral',
        '377' => 'Saavedra',
        '378' => 'Sagrada Familia',
        '379' => 'Salamanca',
        '380' => 'San Antonio',
        '381' => 'San Bernardo',
        '382' => 'San Carlos',
        '383' => 'San Clemente',
        '384' => 'San Esteban',
        '385' => 'San Fabián',
        '386' => 'San Felipe',
        '387' => 'San Fernando',
        '388' => 'San Gregorio',
        '389' => 'San Ignacio',
        '390' => 'San Javier',
        '391' => 'San Joaquín',
        '392' => 'San José de Maipo',
        '393' => 'San Juan de la Costa',
        '394' => 'San Miguel',
        '395' => 'San Nicolás',
        '396' => 'San Pablo',
        '397' => 'San Pedro',
        '398' => 'San Pedro de Atacama',
        '399' => 'San Pedro de la Paz',
        '400' => 'San Rafael',
        '401' => 'San Ramón',
        '402' => 'San Rosendo',
        '403' => 'San Vicente',
        '404' => 'Santa Bárbara',
        '405' => 'Santa Cruz',
        '406' => 'Santa Juana',
        '407' => 'Santa María',
        '408' => 'Santiago',
        '409' => 'Santo Domingo',
        '410' => 'Sierra Gorda',
        '411' => 'Talagante',
        '412' => 'Talca',
        '413' => 'Talcahuano',
        '414' => 'Taltal',
        '415' => 'Temuco',
        '416' => 'Teno',
        '417' => 'Teodoro Schmidt',
        '418' => 'Tierra Amarilla',
        '419' => 'Tiltil',
        '420' => 'Timaukel',
        '421' => 'Tirúa',
        '422' => 'Tocopilla',
        '423' => 'Toltén',
        '424' => 'Tomé',
        '425' => 'Torres del Paine',
        '426' => 'Tortel',
        '427' => 'Traiguén',
        '428' => 'Treguaco',
        '429' => 'Tucapel',
        '430' => 'Valdivia',
        '431' => 'Vallenar',
        '432' => 'Valparaíso',
        '433' => 'Vichuquén',
        '434' => 'Victoria',
        '435' => 'Vicuña',
        '436' => 'Vilcún',
        '437' => 'Villa Alegre',
        '438' => 'Villa Alemana',
        '439' => 'Villarrica',
        '440' => 'Viña del Mar',
        '441' => 'Vitacura',
        '442' => 'Yerbas Buenas',
        '443' => 'Yumbel',
        '444' => 'Yungay',
        '445' => 'Zapallar',
    );

    return $states;
}

function cambio_campos_checkout( $fields ) {
     $fields['billing']['billing_state']['placeholder'] = 'Seleccione una Comuna';
     $fields['billing']['billing_state']['label'] = 'Comuna';

     $fields['shipping']['shipping_state']['placeholder'] = 'Seleccione una Comuna';
     $fields['shipping']['shipping_state']['label'] = 'Comuna';

     unset($fields['billing']['billing_postcode']);
     unset($fields['shipping']['shipping_postcode']);

     return $fields;
}

add_filter('woocommerce_checkout_fields' , 'cambio_campos_checkout');
add_filter('woocommerce_states', 'comunas_de_chile');
?>
